### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [6]:
import numpy as np

In [136]:
# Створення вектора-рядка vector
vector = np.random.uniform(0, 1, 10)
print("Вектор-рядок vector:\n")
print(vector)
print("\nРозмiрнiсть vector:", vector.shape)

Вектор-рядок vector:

[0.86740172 0.85024958 0.30346813 0.9146999  0.02424904 0.07083582
 0.1911273  0.74285104 0.29765089 0.93010383]

Розмiрнiсть vector: (10,)


In [98]:
# Створення вектора-рядка vector2
vector2 = np.random.rand(10)
print("Вектор-рядок vector2:\n")
print(vector2)
print("\nРозмiрнiсть vector2:", vector2.shape)

Вектор-рядок vector2:

[0.62750215 0.611702   0.32984976 0.88967718 0.70741562 0.09245154
 0.10182647 0.61989452 0.60029639 0.74189715]

Розмiрнiсть vector2: (10,)


In [109]:
matrix = []
a_11 = 11
step = 3

for i in range(3):
    row = []
    for j in range(3):
        row.append(a_11)
        a_11 += step
    matrix.append(row)
    
matrix = np.array(matrix)

print("Матриця matrix:")
print(matrix)
print("\nРозмiрнiсть matrix:", matrix.shape)

Матриця matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмiрнiсть matrix: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [138]:
# Операцiї над vector
vector = vector + 10
vector = vector.round(2) 
print(vector)

[10.87 10.85 10.3  10.91 10.02 10.07 10.19 10.74 10.3  10.93]


In [151]:
# Множення matrix на константу 2
matrix_mult_const = 2 * matrix
print("Матриця matrix після множення на константу 2:")
print(matrix_mult_const)

Матриця matrix після множення на константу 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [172]:
# Квадрат vector
squared_vector = vector**2
print(squared_vector)

[118.1569 117.7225 106.09   119.0281 100.4004 101.4049 103.8361 115.3476
 106.09   119.4649]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [196]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [192]:
# Множення матриць A i B
result_matrix = np.dot(B, A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [198]:
# Множення матрицi на вектор C
result_matrix_С = np.dot(result_matrix, C)
print(result_matrix_С)

[[0.5202]
 [0.2846]]


In [200]:
# Множення матрицi на матрицю D
result_matrix_D = np.dot(result_matrix, D)
print(result_matrix_D)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [203]:
# Транспонування матрицi
result_matrix_T = result_matrix.T
print(result_matrix_T)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [219]:
# Транспонування вектору
vector_T = vector.T
print(vector_T)
print("\nРозмiрнiсть vector_T:", vector_T.shape)

[10.87 10.85 10.3  10.91 10.02 10.07 10.19 10.74 10.3  10.93]

Розмiрнiсть vector_T: (10,)


Розмiрнiсть вектора залишилась такою ж як i у вектора vector.

In [225]:
column_vector = np.expand_dims(vector, axis=1)
print(column_vector)
print("\nРозмiрнiсть column_vector:", column_vector.shape)

[[10.87]
 [10.85]
 [10.3 ]
 [10.91]
 [10.02]
 [10.07]
 [10.19]
 [10.74]
 [10.3 ]
 [10.93]]

Розмiрнiсть column_vector: (10, 1)


В результатi застосування операції numpy.expand_dims з вектора-рядка отримали вектор-стовпець.

In [228]:
# Транспонування вектору column_vector
column_vector_T = column_vector.T
print(column_vector_T)
print("\nРозмiрнiсть column_vector_T:", column_vector_T.shape)

[[10.87 10.85 10.3  10.91 10.02 10.07 10.19 10.74 10.3  10.93]]

Розмiрнiсть column_vector_T: (1, 10)
